Nombre = input("gregar nombre")
Apellido = input("agregar apellido")
Ubicacion = input("agregar ubicacion")
Edad =input ("agregar edad")
print("hola te llamas",Nombre,"tu apellido es",Apellido,"estas ubicado en",Ubicacion,"tienes la edad de",Edad)
